### ISSUE TITLE
Consider returning status codes on successful responses too

### ISSUE THREAD

**Issue by mgoldber** [helloalexdodd/full-stack-expense-tracker#3]
It could be an interesting approach to return status codes when you have successfully returned the results as well. This way, on the front end, you can check the code that was received, and also, most backends will tell the user the error status code, _as well as_ the expected status code for a successful response.

https://github.com/helloalexdodd/full-stack-expense-tracker/blob/4c53c3d1b2f68b1ad30113052fab3289e7de01c1/server/lib/controllers/transactions/get-all-transactions.js#L15

Something to consider.

**Comment by helloalexdodd** [comment]
I remember reading somewhere that node sends a 200 status by default, so it's not necessary to include it which is why I haven't included it explicitly here. I'll check that out to make sure that's true though.

Are you also saying that I should also include the expected 200 status code somewhere in the return for all of my errors?

**Comment by mgoldber** [comment]
You are correct! The way you have it should be fine. I'd just stick with the 200. Sometimes on the front-end, it's valuable to check the status code received and then go after the data, but I think the way you have it is pretty sweet.
