### ISSUE TITLE
Confusion around .select('-__v')

### ISSUE THREAD

**Issue by mgoldber** [helloalexdodd/full-stack-expense-tracker#8]
See this syntax a few times throughout the project:

https://github.com/helloalexdodd/full-stack-expense-tracker/blob/820d16a0d4fe724204666f6347e2de5e8333b772/server/lib/controllers/transactions/get-one-transaction.js#L4

I'm probably not understanding, but what is this doing? Is the sorting by most recent version? If so, is there a benefit to doing it this way versus using the createdAt field?

**Comment by helloalexdodd** [comment]
so this is just some weird mongoose syntax. the select method will select particular properties to include in the returned instance if you don't want to include them all, or as in this case with the minus sign in front of it, exclude those particular properties. because the `__v` property is just something mongo adds that serves no purpose to the front end, i excluded it from the return. I haven't done it consistently across the application but I probably will just to tidy up the returns to the front end.

**Comment by mgoldber** [comment]
Ahhh, got it. I'm tired. I think I was thinking 'sort' and typing 'select'. This makes sense! All clear to me.
